### ISSUE TITLE
fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f2\fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f3\fnil\fcharset0 Times;}{\f4\fnil\fcharset0 Georgia ;}}{\colortbl;\red0\green0\blue0;\red0\green0\blue 238blue238;\red 102red102\green 102green102\blue 102blue102;}{\stylesheet{\s0\next0\sqformat\spriority0\fi0\sb0\sa0\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl240\slmult1\rtlch\ab0\ai0\af2\afs22\ltrch\b0\i0\fs22\loch\af2\dbch\af2\hich\f2\strike0\ulnone\cf1 Normal;}{\s1\sbasedon0\snext0\styrsid15694742 \sqformat\spriority0\fi0\sb240\sa240\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl240\slmult1\rtlch\ab\ai0\af2\afs48\ltrch\b\i0\fs48\loch\af2\dbch\af2\hich\f2\strike0\ulnone\cf1 heading 1;}{\s2\sbasedon0\snext0\styrsid15694742

### ISSUE THREAD

**Issue by jbsutton12** [eitch/ch.eitchnet.converter.nokiaandroid#1]
fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f2\fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f3\fnil\fcharset0 Times;}{\f4\fnil\fcharset0 Georgia ;}}{\colortbl;\red0\green0\blue0;\red0\green0\blue 238blue238;\red 102red102\green 102green102\blue 102blue102;}{\stylesheet{\s0\next0\sqformat\spriority0\fi0\sb0\sa0\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl240\slmult1\rtlch\ab0\ai0\af2\afs22\ltrch\b0\i0\fs22\loch\af2\dbch\af2\hich\f2\strike0\ulnone\cf1 Normal;}{\s1\sbasedon0\snext0\styrsid15694742 \sqformat\spriority0\fi0\sb240\sa240\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl240\slmult1\rtlch\ab\ai0\af2\afs48\ltrch\b\i0\fs48\loch\af2\dbch\af2\hich\f2\strike0\ulnone\cf1 heading 1;}{\s2\sbasedon0\snext0\styrsid15694742

**Comment by eitch** [comment]
spam?
